CREATE TABLE CUST_DETAILS
(
  CUST_ID INT NOT NULL,
  CUST_NAME VARCHAR(50),
  CUST_ADD VARCHAR(100),
  CUST_PH VARCHAR(10)
);

CREATE TABLE TRANS_DETAILS
(
  TRANS_ID INT NOT  NULL,
  CUST_ID INT NOT NULL,
  TRANS_MONTH INT(2),
  TRANS_AMT INT
)